robustness engine updates for concurrency
kastenhq/kopia pull request #155
Opened 2021-04-15 14:18 UTC by stevejoachim

The multiclient robustness tests will have multiple clients calling `Engine.ExecAction` concurrently. The goal of this PR is to update the engine `Log` and `Stats` structs so that they can be safely accessed and modified from `Engine.ExecAction` concurrently.

2021-04-15 18:14 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +	)
All this should be atomic

2021-04-15 18:14 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +		e.CumulativeStats.IncrementNoOpCount()
Needs to be atomic

2021-04-15 18:17 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +	)
Consider calling `e.IncrementActionCount()` instead, where
```
func (e *Engine) IncrementActionCount() {
    e.statsMux.Lock()
    defer e.statsMux.Unlock()
    
    // all the critical section logic here
}
```

2021-04-15 18:18 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +	)
Likewise for the decrement logic

2021-04-16 17:37 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +		e.CumulativeStats.NoOpCount++
Got to protect these with the `statsMux`

2021-04-16 17:39 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +func (e *Engine) incrActionCountAndLog(actionKey ActionKey) {
Both these functions should probably be moved to the `stats.go` file. Perhaps also use "stats" as a prefix in the name.

2021-04-16 17:45 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +		e.CumulativeStats.DataPurgeCount++
Suggestion: Put these stats related counter updates into subroutine which accepts some sort of discriminator. Then one can safely protect them under all circumstances. e.g.
```
func (e *Engine) statsUpdateCounters(updateType string) {
	e.statsMux.Lock()
	defer e.statsMux.Unlock()
	switch updateType {
         case "incr-no-op": ...
         case "incr-data-purge":  ...
         case "incr-data-restore": ... 
         case "incr-error-recovery": ...
        }
}
```

2021-04-16 17:46 UTC, carlbraganza requested changes
minor changes

2021-04-16 18:56 UTC, stevejoachim commented
@carlbraganza Thank you for catching those issues and suggesting a better way to structure everything.

I made some changes based on your feedback. Please let me know what you think.

2021-04-16 20:03 UTC, carlbraganza commented on tests/robustness/engine/stats.go
> +	incrErrorRecovery
Could have used "stats" as a prefix here too :-)

2021-04-16 20:05 UTC, carlbraganza commented on tests/robustness/engine/action.go
> +func (e *Engine) logCompleted(logEntry *LogEntry, err error) {
This function should be moved to `log.go`

2021-04-16 20:05 UTC, carlbraganza approved these changes

2021-04-16 20:34 UTC, stevejoachim commented
Thanks, I made the changes you suggested.

2021-04-21 17:47 UTC, merged